import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { AppWrapper } from "@/context";

const PlusJakartaSans = localFont( {
  src: "./fonts/PlusJakartaSans-VariableFont_wght.ttf",
  variable: "--font-plus-jakarta-sans",
  weight: "100 900",
} );
const PlusJakartaSansItalic = localFont( {
  src: "./fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf",
  variable: "--font-plus-jakarta-sans-italic",
  weight: "100 900",
} );

export const metadata: Metadata = {
  title: {
    default: "Kanban Management App",
    template: "%s | Kanban Management App",
  },
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={ `${ PlusJakartaSans.variable } ${ PlusJakartaSansItalic.variable } antialiased ` }
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppWrapper>
            <main>
              { children }
            </main>
          </AppWrapper>
        </ThemeProvider>
      </body>
    </html >
  );
}
