import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ThemeProvider } from "@/components/theme-provider"

const PlusJakartaSans = localFont( {
  src: "./fonts/PlusJakartaSans-VariableFont_wght.ttf",
  variable: "--font-plus-jakarta-sans",
  weight: "100 900",
} );
const PlusJakartaSansItalic = localFont( {
  src: "./fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf",
  variable: "--font-plus-jakarta-sans-italic",
  weight: "100 900",
} );

export const metadata: Metadata = {
  title: "Kanban Management App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={ `${ PlusJakartaSans.variable } ${ PlusJakartaSansItalic.variable } antialiased overscroll-none` }
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <main>
              { children }
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
